# Generated by Django 5.2.17 on 2026-08-30 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('mailing_address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('consent_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Token for the no-login consent link emailed to the bearer.', unique=True)),
                ('consent_requested_at', models.DateTimeField(blank=True, null=True)),
                ('next_season_consent_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('declined', 'Declined')], default='pending', help_text="Consent to be contacted about next year's Bike + Brew.", max_length=10)),
                ('next_season_consent_responded_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_consent_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('declined', 'Declined')], default='pending', help_text='Consent to be contacted about other Make Your Mark events/merchandise.', max_length=10)),
                ('marketing_consent_responded_at', models.DateTimeField(blank=True, null=True)),
                ('retention_expiry_date', models.DateField(blank=True, help_text='Purge-due date for a declined/non-responding bearer, set when an admin runs the retention purge review (§5.6).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. '2026'.", max_length=20, unique=True)),
                ('is_current', models.BooleanField(default=False, help_text='The season new submissions default to (§5.2).')),
                ('raffle_concluded_at', models.DateField(blank=True, help_text="When this season's raffle draw/processing concluded — starts the retention grace period (§5.6).", null=True)),
                ('retention_grace_period_days', models.PositiveIntegerField(default=90, help_text="Days after raffle_concluded_at before a declined/non-responding bearer's data is purged (§9 — admin-configurable; spec sets no fixed default).")),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='Passport number, 1-296.', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text="Uncheck instead of deleting if a venue drops out of a season's list.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PassportSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_number', models.PositiveIntegerField(help_text='Sequential number assigned when the physical passport is logged in, before data entry — prevents duplicate/missed processing (§5.2).')),
                ('date_received', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('entered', 'Entered'), ('emailed', 'Emailed')], default='received', max_length=10)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_send_failed', models.BooleanField(default=False, help_text='Flagged for staff follow-up if the confirmation email bounced or failed to send (§5.3) — a failure must be visible, not silent.')),
                ('notes', models.TextField(blank=True, help_text='Anomalies, e.g. ambiguous stamp, duplicate cafe stamps.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bearer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='passports.bearer')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_submissions', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='passports.season')),
                ('venues_stamped', models.ManyToManyField(blank=True, related_name='submissions', to='passports.venue')),
            ],
            options={
                'ordering': ['season', 'intake_number'],
                'constraints': [models.UniqueConstraint(fields=('season', 'intake_number'), name='unique_intake_number_per_season')],
            },
        ),
    ]
