# Generated by Django 5.2.17 on 2026-08-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='email',
            field=models.EmailField(blank=True, help_text='Often not collected — bearers skew older and this is an old-school charity. Phone is the more reliable match key.', max_length=254),
        ),
    ]
