# Generated by Django 5.2.17 on 2026-08-31 16:02

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0002_alter_bearer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBearer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Often not collected — bearers skew older and this is an old-school charity. Phone is the more reliable match key.', max_length=254)),
                ('mailing_address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('consent_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token for the no-login consent link emailed to the bearer.')),
                ('consent_requested_at', models.DateTimeField(blank=True, null=True)),
                ('next_season_consent_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('declined', 'Declined')], default='pending', help_text="Consent to be contacted about next year's Bike + Brew.", max_length=10)),
                ('next_season_consent_responded_at', models.DateTimeField(blank=True, null=True)),
                ('marketing_consent_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('declined', 'Declined')], default='pending', help_text='Consent to be contacted about other Make Your Mark events/merchandise.', max_length=10)),
                ('marketing_consent_responded_at', models.DateTimeField(blank=True, null=True)),
                ('retention_expiry_date', models.DateField(blank=True, help_text='Purge-due date for a declined/non-responding bearer, set when an admin runs the retention purge review (§5.6).', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bearer',
                'verbose_name_plural': 'historical bearers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPassportSubmission',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('intake_number', models.PositiveIntegerField(help_text='Sequential number assigned when the physical passport is logged in, before data entry — prevents duplicate/missed processing (§5.2).')),
                ('date_received', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('entered', 'Entered'), ('emailed', 'Emailed')], default='received', max_length=10)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_send_failed', models.BooleanField(default=False, help_text='Flagged for staff follow-up if the confirmation email bounced or failed to send (§5.3) — a failure must be visible, not silent.')),
                ('notes', models.TextField(blank=True, help_text='Anomalies, e.g. ambiguous stamp, duplicate cafe stamps.')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bearer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passports.bearer')),
                ('entered_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passports.season')),
            ],
            options={
                'verbose_name': 'historical passport submission',
                'verbose_name_plural': 'historical passport submissions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPassportSubmission_venues_stamped',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='passports.historicalpassportsubmission')),
                ('passportsubmission', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passports.passportsubmission')),
                ('venue', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passports.venue')),
            ],
            options={
                'verbose_name': 'HistoricalPassportSubmission_venues_stamped',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
