# Generated by Django 5.2.17 on 2026-08-31 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0003_historicalbearer_historicalpassportsubmission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpassportsubmission',
            name='intake_number',
            field=models.PositiveIntegerField(help_text="Sequential number auto-assigned per season, the first time this submission's venues are saved. Combined with the one-submission-per-bearer-per-season rule below, this is effectively 'the Nth bearer processed this season' (§5.2)."),
        ),
        migrations.AlterField(
            model_name='passportsubmission',
            name='intake_number',
            field=models.PositiveIntegerField(help_text="Sequential number auto-assigned per season, the first time this submission's venues are saved. Combined with the one-submission-per-bearer-per-season rule below, this is effectively 'the Nth bearer processed this season' (§5.2)."),
        ),
        migrations.AddConstraint(
            model_name='passportsubmission',
            constraint=models.UniqueConstraint(fields=('bearer', 'season'), name='unique_bearer_per_season'),
        ),
    ]
