# Generated by Django 5.2.17 on 2026-08-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0004_alter_historicalpassportsubmission_intake_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='phone',
            field=models.CharField(error_messages={'unique': 'A bearer with this phone number already exists — search for them instead of creating a new record.'}, help_text="Stored normalized (E.164, e.g. +447990575555). The mandatory, unique key for matching an existing bearer — not email, which many bearers don't have.", max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbearer',
            name='phone',
            field=models.CharField(db_index=True, error_messages={'unique': 'A bearer with this phone number already exists — search for them instead of creating a new record.'}, help_text="Stored normalized (E.164, e.g. +447990575555). The mandatory, unique key for matching an existing bearer — not email, which many bearers don't have.", max_length=30),
        ),
    ]
