# Generated by Django 5.2.17 on 2026-08-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0005_alter_bearer_phone_alter_historicalbearer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='page_group',
            field=models.CharField(blank=True, help_text="Which physical passport page-spread this venue appears on (e.g. 'img001.pdf') — groups venues into pages for the intake form's Book view (§5.2). Pages can have fewer than 12 venues where the original book had section-divider artwork instead of a full page of listings.", max_length=50),
        ),
    ]
