# Generated by Django 5.2.17 on 2026-09-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0009_grant_site_admin_raffleexport_view'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_season'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(condition=models.Q(('number__gte', 1), ('number__lte', 296)), name='venue_number_in_range'),
        ),
    ]
