# Generated by Django 5.2.17 on 2026-09-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0010_season_unique_current_season_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-name'], 'permissions': [('is_site_admin', 'Can access the dashboard, audit log, and raffle export (site admin)')]},
        ),
    ]
