# Generated by Django 5.2.17 on 2026-09-02 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0012_grant_site_admin_is_site_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(blank=True, help_text="Optional label the host can type in before drawing, e.g. 'Weekend for two'.", max_length=200)),
                ('ticket_count', models.PositiveIntegerField(help_text="Bearer's raffle ticket count at the moment they were drawn — the odds they actually had.")),
                ('drawn_at', models.DateTimeField(auto_now_add=True)),
                ('bearer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffle_wins', to='passports.bearer')),
                ('drawn_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raffle_winners_drawn', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffle_winners', to='passports.season')),
            ],
            options={
                'ordering': ['-drawn_at'],
                'constraints': [models.UniqueConstraint(fields=('season', 'bearer'), name='unique_winner_per_season')],
            },
        ),
    ]
