# Generated by Django 5.2.17 on 2026-09-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0014_grant_site_admin_view_rafflewinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafflewinner',
            name='ticket_number',
            field=models.CharField(blank=True, default='', help_text="Randomly assigned 5-digit number (09999–99999) revealed for this draw's slot-machine animation — generated at draw time, not a pre-printed physical ticket ID.", max_length=5),
        ),
    ]
