# Generated by Django 5.2.17 on 2026-09-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0016_emailcampaign_historicalemailcampaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer',
            name='mailing_address',
            field=models.TextField(blank=True, help_text='Not always collected — some bearers only give a phone number.'),
        ),
        migrations.AlterField(
            model_name='historicalbearer',
            name='mailing_address',
            field=models.TextField(blank=True, help_text='Not always collected — some bearers only give a phone number.'),
        ),
    ]
