# Generated by Django 5.2.17 on 2026-09-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0017_alter_bearer_mailing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpassportsubmission',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Set the first time a Passport Logger saves this submission and exits the intake form. A locked submission — and its bearer — can no longer be edited by a Logger, only by a Site Admin or superuser; see access.is_submission_editable/is_bearer_editable.', null=True),
        ),
        migrations.AddField(
            model_name='passportsubmission',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='Set the first time a Passport Logger saves this submission and exits the intake form. A locked submission — and its bearer — can no longer be edited by a Logger, only by a Site Admin or superuser; see access.is_submission_editable/is_bearer_editable.', null=True),
        ),
    ]
