# Generated by Django 5.2.17 on 2026-09-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0018_historicalpassportsubmission_locked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="Sequential per season, zero-padded, e.g. '000001'.", max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raffle_tickets', to='passports.season')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_numbers', to='passports.passportsubmission')),
            ],
            options={
                'ordering': ['season', 'number'],
                'constraints': [models.UniqueConstraint(fields=('season', 'number'), name='unique_raffle_ticket_number_per_season')],
            },
        ),
    ]
