# Generated by Django 5.2.17 on 2026-09-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0019_raffleticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafflewinner',
            name='ticket',
            field=models.OneToOneField(blank=True, help_text='The issued ticket actually drawn. Null only for winners drawn before the draw switched to issued numbers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='win', to='passports.raffleticket'),
        ),
        migrations.AlterField(
            model_name='rafflewinner',
            name='ticket_count',
            field=models.PositiveIntegerField(help_text="Bearer's issued raffle ticket count at the moment they were drawn — the odds they actually had."),
        ),
        migrations.AlterField(
            model_name='rafflewinner',
            name='ticket_number',
            field=models.CharField(blank=True, default='', help_text="The drawn ticket's number (a copy of ticket.number, so the record reads on its own) — the same number the bearer was sent in their confirmation email.", max_length=6),
        ),
    ]
