# Generated by Django 5.2.17 on 2026-09-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0020_raffle_winner_issued_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('reply_to', models.CharField(blank=True, help_text='Email or phone the sender gave for a reply (optional).', max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert_sent', models.BooleanField(default=False, help_text='Whether the staff alert email went out.')),
                ('handled', models.BooleanField(default=False, help_text='Tick once someone has dealt with this message.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
