# Generated by Django 5.2.17 on 2026-09-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0022_grant_site_admin_publicmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmessage',
            name='ambassador_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='inkpad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='passports_collected',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number collected'),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='report_date',
            field=models.DateField(blank=True, help_text='The day the report was sent (set automatically).', null=True),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='stamp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='unused_passports',
            field=models.BooleanField(default=False, verbose_name='unused passports'),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='unused_stationery',
            field=models.BooleanField(default=False, verbose_name='unused stationery'),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='venue_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicmessage',
            name='message',
            field=models.TextField(blank=True, max_length=2000, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='publicmessage',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ambassador name'),
        ),
    ]
