# Generated by Django 5.2.17 on 2026-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0023_publicmessage_ambassador_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmessage',
            name='second_stamp',
            field=models.BooleanField(default=False, verbose_name='2nd stamp'),
        ),
    ]
