# Generated by Django 5.2.17 on 2026-10-01 21:26

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0025_bearer_consent_asked_at_intake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmessage',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='venue_reports', to='passports.season'),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='passports.venue'),
        ),
        migrations.CreateModel(
            name='HistoricalVenueSeason',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('recovery_status', models.CharField(choices=[('outstanding', 'Outstanding'), ('collected', 'Collected'), ('kept', 'Kept at venue for next year'), ('lost', 'Lost')], default='outstanding', max_length=12, verbose_name='kit recovery')),
                ('recovery_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passports.season')),
                ('venue', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='passports.venue')),
            ],
            options={
                'verbose_name': 'historical venue by season',
                'verbose_name_plural': 'historical venues by season',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VenueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_status', models.CharField(choices=[('outstanding', 'Outstanding'), ('collected', 'Collected'), ('kept', 'Kept at venue for next year'), ('lost', 'Lost')], default='outstanding', max_length=12, verbose_name='kit recovery')),
                ('recovery_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='passports.season')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='passports.venue')),
            ],
            options={
                'verbose_name': 'venue by season',
                'verbose_name_plural': 'venues by season',
                'ordering': ['-season__name', 'venue__number'],
                'constraints': [models.UniqueConstraint(fields=('venue', 'season'), name='one_row_per_venue_per_season')],
            },
        ),
    ]
