# Generated by Django 5.2.17 on 2026-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0027_link_reports_grant_venueseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicmessage',
            name='validation_collected',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='number collected'),
        ),
        migrations.AddField(
            model_name='publicmessage',
            name='validation_passports',
            field=models.BooleanField(default=False, verbose_name='passports for validation'),
        ),
    ]
